#
# Module manifest for module 'Microsoft-Secure-Score-Assessment-Toolkit'
#
# Generated by: Mohammed Siddiqui
#
# Generated on: 2025-11-14
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Microsoft-Secure-Score-Assessment-Toolkit.psm1'

# Version number of this module.
ModuleVersion = '2.2.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'd61fcf0d-d7d1-4d29-a107-a8709c612d47'

# Author of this module
Author = 'Mohammed Siddiqui'

# Company or vendor of this module
CompanyName = 'Community'

# Copyright statement for this module
Copyright = '(c) 2025-present Mohammed Siddiqui. All rights reserved. MIT License.'

# Description of the functionality provided by this module
Description = 'A powerful PowerShell toolkit for assessing Microsoft 365 security posture through the Microsoft Secure Score API. Generate comprehensive, interactive HTML reports with 411+ security controls directly from Microsoft Graph API. Features include real-time data fetching, interactive filtering, floating action buttons, and direct links to configuration portals. Perfect for security assessments, compliance reporting, and continuous security monitoring.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Connect-MicrosoftSecureScore',
    'Disconnect-MicrosoftSecureScore',
    'Invoke-MicrosoftSecureScore',
    'Get-MicrosoftSecureScoreInfo'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'Microsoft-Secure-Score-Assessment-Toolkit.psm1',
    'Microsoft-Secure-Score-Assessment-Toolkit.psd1',
    'README.md',
    'CHANGELOG.md',
    'powershellnerdlogo.png',
    'Core/GraphApiClient.ps1',
    'Core/Logger.ps1',
    'Core/Models.ps1',
    'Processors/ComplianceProcessor.ps1',
    'Processors/UrlProcessor.ps1',
    'Reports/HtmlReportGenerator.ps1',
    'Config/control-mappings.json',
    'Templates/report-modern-template.html'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Microsoft365', 'M365', 'SecureScore', 'Security', 'Compliance', 'Audit', 'Assessment', 'Graph', 'GraphAPI', 'SecurityCompliance', 'SecurityAssessment', 'SecurityPosture', 'CyberSecurity', 'GRC', 'RiskManagement', 'SecurityControls', 'EntraID', 'AzureAD', 'Defender', 'Purview', 'Intune')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/mohammedsiddiqui6872/Microsoft-Secure-Score-Assessment-Toolkit/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/mohammedsiddiqui6872/Microsoft-Secure-Score-Assessment-Toolkit'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/mohammedsiddiqui6872/Microsoft-Secure-Score-Assessment-Toolkit/main/.github/icon.png'

        # ReleaseNotes of this module
        ReleaseNotes = @'
v2.2.0 CSV Export, Bug Fixes, and Quality Improvements

NEW FEATURES
- CSV Export: New -CsvPath parameter exports all control data to CSV for spreadsheet analysis
- Disconnect Function: New Disconnect-MicrosoftSecureScore for proper session cleanup
- No-Open Switch: New -NoOpen parameter suppresses automatic browser launch

BUG FIXES
- Fixed division by zero when MaxScore is 0
- Fixed missing closing div in HTML template causing layout issues
- Fixed JavaScript filter crash in Firefox/Safari (implicit event variable)
- Fixed score of 0 being silently dropped in report metadata
- Fixed internal functions being leaked to user session (namespace pollution)
- Fixed loading overlay never displaying
- Fixed URL mapping using substring match instead of exact match
- Fixed emoji characters showing as garbled text in reports
- Fixed progress bar counting excluded controls incorrectly
- Removed duplicate LinkedIn link in floating action menu
- Removed stale third-party email from help function

IMPROVEMENTS
- O(n^2) array performance replaced with List collection
- Removed redundant Import-Module calls across all functions
- Removed dead JavaScript code (unused functions, setInterval, deprecated APIs)
- Eliminated duplicate HTML stripping code in ComplianceProcessor
- Version now read from manifest instead of hardcoded
- Path validation for ReportPath, LogPath, and CsvPath
- Replaced emoji characters with SVG icons for encoding compatibility
- Updated info function with current features

Full changelog at https://github.com/mohammedsiddiqui6872/Microsoft-Secure-Score-Assessment-Toolkit/blob/main/CHANGELOG.md
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/mohammedsiddiqui6872/Microsoft-Secure-Score-Assessment-Toolkit/blob/main/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
